name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Set Heroku Stack to Container
    - name: Set Heroku Stack
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku stack:set container -a app

    # Add additional steps for deploying your app
